### ISSUE TITLE
网络环境不太好时，手机上播放卡住后无法自己恢复播放

### ISSUE THREAD

**Issue by Susy123** [ErosZy/WXInlinePlayer#41]
网络环境不太好时，手机上画面会卡住，显示可播放时长不变，进度秒数还会一直增加，解码平均只有十几ms，单元平均0ms。

网络恢复正常后，查看network信息，后续视频flv信息一致有正常加载进来，但是手机画面仍然不会继续播放，仍然显示可播放时长不变，进度秒数还会一直增加，解码平均只有十几ms，单元平均0ms。（测试手机为ios10和ios13，似为普遍现象）

在pc端chrome调试，模拟网络环境不好，画面虽然也卡顿，但是进度秒数不会大于可播放时长，等待后续flv资源加载进来后，画面能够继续播放。

请问大家有没有碰到这个问题，有什么解决思路？
（ps:同一个测试用视频源，在网络环境好的情况下是能够流畅播放完成的。）

**Comment by Susy123** [comment]
在网络情况不好时，
https://github.com/qiaozi-tech/WXInlinePlayer/blob/f840c7adf5a43d3497cd5f8a74b6d95af7cdbea2/lib/codec/src/factor/codec_factor.cpp#L292
这一部分代码就不再执行，即使网络恢复，也不再postMessage去push frames，frames里缓存的数据绘制消耗完后，页面就卡住不再动了。

c++部分不太熟，还请作者大大看一下 。

**Comment by ErosZy** [comment]
如何模拟？

**Comment by Susy123** [comment]
@ErosZy 手机连接热点，然后热点设置采用3g网络，可以尝试加载该视频：http://s3.cn-north-1.amazonaws.com.cn/cft-3g-test/cft/interaction/cfd76fdb6e5d472f9c9ee80e0d42e20a.flv

（chrome上模拟lower 3g不会复现，chrome上遇到网络卡顿，等待获取到新的视频数据后，能够继续播放。

**Comment by ErosZy** [comment]
必须要手机才能复现么？

**Comment by ErosZy** [comment]
@Susy123 请使用1.3.5，看是否还会有此类问题出现。

**Comment by Firstnote** [comment]
> @Susy123 请使用1.3.6，看是否还会有此类问题出现。

最新的example 本地换上面的那个flv源，chrome直接就报错了，是否对flv源有特殊的要求，报错图片github暂时传不上来

**Comment by ErosZy** [comment]
@Firstnote 测试没问题，上面的源是H264的，example请取消H265的设置。

**Comment by Firstnote** [comment]
> @Firstnote 测试没问题，上面的源是H264的，example请取消H265的设置。

ok，确实
