### ISSUE TITLE
部分http-flv链接播放报错：memory access out of bounds

### ISSUE THREAD

**Issue by JS-Hao** [ErosZy/WXInlinePlayer#48]
问题描述：
大佬你好，我按demo案例运行了部分http-flv，发现在wasm模块会出现以下错误，导致无法demux & decode，截图如下：
![image](https://user-images.githubusercontent.com/16398869/90946884-f6b25900-e463-11ea-8ae4-c6cf81d9f24a.png)

播放器配置代码如下：
```javascript

// initial
WXInlinePlayer.init({
  wasmUrl: "./prod.all.wasm.combine.js", // 直接使用了项目自带编译后的文件 ./example/prod.all.wasm.combine.js
});

const player = new WXInlinePlayer({
  url: "./test.flv",
  $container: $canvas,
  hasVideo: true,
  hasAudio: true,
  volume: 1,
  muted: false,
  autoplay: true,
  loop: true,
  isLive: false,
  chunkSize: 131072,
  preloadTime: 500,
  bufferingTime: 500,
  cacheSegmentCount: 64,
  customLoader: null,
});
```

运行环境：Chrome 84.0.4147.135（正式版本）
flv文件：
[test.flv.zip](https://github.com/qiaozi-tech/WXInlinePlayer/files/5111858/test.flv.zip)

希望大佬可以百忙之中抽空解答，不胜感激

**Comment by yingchengpa** [comment]
test.flv 先用ksvc的ffmpeg版本验证下是否可以正常解析；
我也碰到你这个问题，但是只要flv 保存的没问题，这个播放器就可以播放

**Comment by ErosZy** [comment]
The question has not been answered for a long time, so we are temporarily closing this issue, so please reopen it if you have other questions.

**Comment by RomeoAndJulietAndMe** [comment]
> test.flv 先用ksvc的ffmpeg版本验证下是否可以正常解析；
> 我也碰到你这个问题，但是只要flv 保存的没问题，这个播放器就可以播放

兄弟你使用WXInlinePlayer的时候，视频不卡顿吗

**Comment by yingchengpa** [comment]
我已经不用这个播放器了。免费你可以看看easyplayer.js 有1s的延时；收费用nodeplayer.js 零延时



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: RomeoAndJulietAndMe ***@***.***&gt;
发送时间: 2021年6月29日 09:37
收件人: ErosZy/WXInlinePlayer ***@***.***&gt;
抄送: yingcheng ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ErosZy/WXInlinePlayer] 部分http-flv链接播放报错：memory access out of bounds (#48)





  
test.flv 先用ksvc的ffmpeg版本验证下是否可以正常解析；
 我也碰到你这个问题，但是只要flv 保存的没问题，这个播放器就可以播放
  
兄弟你使用WXInlinePlayer的时候，视频不卡顿吗

**Comment by JohnApache** [comment]
这个issue目前关闭了是已经有解决方案吗？我也遇到同样的问题了，用ffmpeg 可以正常解析， 
![image](https://user-images.githubusercontent.com/25084030/129823666-89aecc39-31f8-47d3-b7ed-f0a3f842c06f.png)
， 我也是用了项目自带编译后的文件 尝试了， 也是报的同样的问题，
