### ISSUE TITLE
obs推流 增加 b帧设置 播放卡顿 控制台 报错

### ISSUE THREAD

**Issue by changanweb** [ErosZy/WXInlinePlayer#52]
![QQ图片20200921164638](https://user-images.githubusercontent.com/71634193/93747941-0c18cf80-fc2a-11ea-883c-ae6ade15ba3e.png)
![QQ图片20200921164643](https://user-images.githubusercontent.com/71634193/93747966-13d87400-fc2a-11ea-8767-ff857d039299.png)

obs推流 增加 b帧设置 播放卡顿 控制台 报错，是因为openh264不支持b帧吗？

[OpenH264] this = 0x0x50e060, Error:DecodeCurrentAccessUnit()::::::PrefetchPic ERROR, pSps->iNumRefFrames:3.

**Comment by ErosZy** [comment]
OpenH264支持部分B帧解码，请参考OpenH264相关说明。
