### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by wnpllrzodiac** [ErosZy/WXInlinePlayer#53]
dist/index.js    65.85 KB    79.18s
+ mv dist/index.js ./example
+ cd lib/codec
+ bash build.sh
+ rm -rf ./bin
+ rm -rf ./build
+ mkdir ./build
+ cd ./build
+ node ../tool/compile.js wasm baseline
+ emcmake cmake ..
CMake Error at /root/work/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake:105 (message):
  Failed to fetch compiler version information with command
  "'/root/work/emsdk/fastcomp/emscripten/emcc' -v"! Process returned with
  error code 1.
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
+ emmake make -j 4
make: ['make', '-j', '4']
make: *** No targets specified and no makefile found.  Stop.
+ mv ../bin/prod.js ../bin/baseline.wasm.js
mv: cannot stat ‘../bin/prod.js’: No such file or directory
+ node ../tool/compile.js asm baseline
+ emcmake cmake ..
CMake Error at /root/work/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake:105 (message):
  Failed to fetch compiler version information with command
  "'/root/work/emsdk/fastcomp/emscripten/emcc' -v"! Process returned with
  error code 1.
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93

**Comment by wnpllrzodiac** [comment]
cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

cmake --version
cmake version 3.17.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu

**Comment by wnpllrzodiac** [comment]
/root/work/emsdk/fastcomp/emscripten/emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.45
/root/work/emsdk/fastcomp/fastcomp/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/clang)
/root/work/emsdk/fastcomp/fastcomp/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/clang)
/root/work/emsdk/fastcomp/fastcomp/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/../lib/libLLVM-6.0.so)
/root/work/emsdk/fastcomp/fastcomp/bin/clang: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/../lib/libLLVM-6.0.so)
/root/work/emsdk/fastcomp/fastcomp/bin/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/clang++)
/root/work/emsdk/fastcomp/fastcomp/bin/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/clang++)
/root/work/emsdk/fastcomp/fastcomp/bin/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/../lib/libLLVM-6.0.so)
/root/work/emsdk/fastcomp/fastcomp/bin/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/work/emsdk/fastcomp/fastcomp/bin/../lib/libLLVM-6.0.so)
shared:ERROR: '/root/work/emsdk/fastcomp/fastcomp/bin/clang++ --version' failed (1)

**Comment by wnpllrzodiac** [comment]
glibc problem means this lib cannot build on centos7.8?
because emsdk v1.38.45 so was pre-built.

**Comment by ErosZy** [comment]
OSX/Ubuntu/WSL2 is just ok, you can try.
