### ISSUE TITLE
ios下开启侧边静音，则视频静音

### ISSUE THREAD

**Issue by mrzxc** [ErosZy/WXInlinePlayer#54]
ios下开启侧边静音，则视频静音，查阅是由于AudioContext带来的，原生的audio标签和video标签不受影响，是否可修复？

**Comment by ErosZy** [comment]
Audio没有AudioContext的相关API能够支持流式Chunk播放，因此这个问题没有办法解决。

**Comment by mrzxc** [comment]
好的，谢谢

> Audio没有AudioContext的相关API能够支持流式Chunk播放，因此这个问题没有办法解决。

**Comment by lvsenlin** [comment]
这个呢？
decodeAudioData：https://developer.mozilla.org/zh-CN/docs/Web/API/AudioContext/decodeAudioData
