### ISSUE TITLE
播放直播视频时，音频有明显噪声

### ISSUE THREAD

**Issue by mrzxc** [ErosZy/WXInlinePlayer#55]
音频解析有明显噪声，偶发，但是方法可以必现
必现方法：开始的时候我尝试使用播放无声的音频来实现自动播放检测（检测浏览器自动播放限制）即直播音频和这段无声音频会同时播放，但是发现WXInlinePlayer解析的音频会有很大噪声。
但是后来发现去掉这段音频，也会噪声这种情况，但是刷新页面就好了。
推测原因： 1. IOS本身的解析可能有bug 
请问是否遇到这种问题，有没有解决方案？

**Comment by ErosZy** [comment]
参考：https://github.com/ErosZy/WXInlinePlayer/issues/39
如果要解决你们这个问题，需要可以mute掉音频。
