### ISSUE TITLE
解码大分辨率性能不够的时候有花屏现象，edge（chrome内核）无显示，但是在解码

### ISSUE THREAD

**Issue by lostfordream** [ErosZy/WXInlinePlayer#56]
谢谢大佬的开源，测试中发现2个问题
1.解码大分辨率性能不够的时候有花屏现象，
2.edge（chrome内核）无显示，但是在解码

**Comment by ErosZy** [comment]
@lostfordream 请提供源或者示例文件

**Comment by ErosZy** [comment]
The question has not been answered for a long time, so we are temporarily closing this issue, so please reopen it if you have other questions.
