### ISSUE TITLE
H265 1080P 3000码率，在pc端能同时拉起几录？

### ISSUE THREAD

**Issue by wangpeng1** [ErosZy/WXInlinePlayer#60]
你好，想和你讨论一下这方面技术，后期可以合作，你的微信多少？我的微信13335009963

**Comment by ErosZy** [comment]
H265使用软解存在性能问题，PC上针对3000码率的H265视频实际上解码压力很大，不建议使用。

**Comment by RomeoAndJulietAndMe** [comment]
您好，您的视频项目使用WXInlinePlayer成功了么？卡顿吗？延迟么？
