### ISSUE TITLE
[feature request] 希望让用户自行判断使用asm还是wasm

### ISSUE THREAD

**Issue by ouzhou** [ErosZy/WXInlinePlayer#61]
源码是用parcel打包的，用webpack打包似乎文件不允许用内联代码的形式，会抛出错误，只能通过写一个script标签引入，然后这个库自行提供了一个init加载不同的脚本的方法，这让在工程化前端很难使用，比如封装到react vue里面

**Comment by ErosZy** [comment]
我比较熟悉Parcel，但是Webpack不太熟，如果这块你比较熟悉可以提供PR。
