### ISSUE TITLE
设置canvas截图，返回空白图片问题

### ISSUE THREAD

**Issue by guygubaby** [ErosZy/WXInlinePlayer#63]
通过 `canvas.toBlob` 设置`截图`，返回的都是`空白图片`，查询资料得知需要使用
```js
const gl = canvas.getContext('webgl', {
      preserveDrawingBuffer: true
})
```
[源码使用的是](https://github.com/ErosZy/WXInlinePlayer/blob/beb52fb2818e0371c797d281ddac9154185271df/src/drawer/drawer.js#L185)，所以不能得到有效的blob,麻烦问下有什么办法可以解决

或者可以手动调用绘制方法([资料](https://webglfundamentals.org/webgl/lessons/webgl-tips.html))后截图，请问是否可以手动调用[绘制函数](https://github.com/ErosZy/WXInlinePlayer/blob/beb52fb2818e0371c797d281ddac9154185271df/src/drawer/drawer.js#L95)

**Comment by RomeoAndJulietAndMe** [comment]
这位兄台，wxinlineplayer使用起来后，你的不卡顿吗

**Comment by RomeoAndJulietAndMe** [comment]
还有这位兄台，改了未压缩的src里面代码，按照作者的bash build.sh命令操作，你的会编译报错吗 怎么解决呀
![Uploading image.png…](
)

**Comment by RomeoAndJulietAndMe** [comment]
截图似乎打不开，我再发一下子。
![image](https://user-images.githubusercontent.com/48921406/123590512-51070d80-d81d-11eb-999f-ece6946bf83b.png)

**Comment by guygubaby** [comment]
> 这位兄台，wxinlineplayer使用起来后，你的不卡顿吗

我没用这个了，用的 easy-player 😂
