### ISSUE TITLE
在官方的Demo后跟换其他的url不能播放

### ISSUE THREAD

**Issue by mooczhou** [ErosZy/WXInlinePlayer#64]
更换url播放
http://bofang.672582.com/live/livestream/esl_csgo.flv
正常播放：
![image](https://user-images.githubusercontent.com/23721965/108180200-73876c80-7141-11eb-8075-0e24ff3aa658.png)
不能播放：
![image](https://user-images.githubusercontent.com/23721965/108180354-a03b8400-7141-11eb-8958-5a4ddcb9df36.png)

**Comment by ErosZy** [comment]
播放地址不可访问

**Comment by mooczhou** [comment]
这个播放地址是我自己推送的

**Comment by RomeoAndJulietAndMe** [comment]
> 这个播放地址是我自己推送的，我用VLC是可以播放的

你得把这个地址在代码里面修改。
