### ISSUE TITLE
not issue，just curious

### ISSUE THREAD

**Issue by lengjing** [ErosZy/WXInlinePlayer#71]
Readme 中 手淘 h265 和花椒 h265 方案有相关链接吗？

**Comment by ErosZy** [comment]
自行找到他们的播放器页面，然后剥离代码进行测试

**Comment by RomeoAndJulietAndMe** [comment]
> Readme 中 手淘 h265 和花椒 h265 方案有相关链接吗？

这位兄弟 你找到h265的可行的播放器了没～

**Comment by lengjing** [comment]
@RomeoAndJulietAndMe 
没有，还是用的 video + video mse + ffmpeg wasm

**Comment by RomeoAndJulietAndMe** [comment]
> @RomeoAndJulietAndMe
> 没有，还是用的 video + video mse + ffmpeg wasm

兄弟这个能播放h265的编码格式么？播放过程卡顿或者延迟么？这个WXInlinePlayer怎么没用上呀？

**Comment by RomeoAndJulietAndMe** [comment]
> @RomeoAndJulietAndMe
> 没有，还是用的 video + video mse + ffmpeg wasm
你的能播放h265的么？怎没有用wxinlineplayer嘞？
