### ISSUE TITLE
啊！我看文中提了手机端，那pc端也能用这个WXinlinePlayer吗？性能方面不会受影响吧？

### ISSUE THREAD

**Issue by RomeoAndJulietAndMe** [ErosZy/WXInlinePlayer#75]

**Comment by ErosZy** [comment]
需要根据你的视频码率来进行测试。

**Comment by RomeoAndJulietAndMe** [comment]
我和同事调试了好些天，几秒时间就卡顿一下，这个一直解决不了

**Comment by RomeoAndJulietAndMe** [comment]
![image](https://user-images.githubusercontent.com/48921406/123088358-3406bf00-d458-11eb-99b8-7a364a0de856.png)
------------
作者呀这个bash build.sh出现这个怎么回事嘞

**Comment by RomeoAndJulietAndMe** [comment]
> 需要根据你的视频码率来进行测试。
作者呀这个bash build.sh出现这个怎么回事嘞
![image](https://user-images.githubusercontent.com/48921406/123187503-df515b80-d4cc-11eb-9738-eb20fbceafb6.png)

**Comment by RomeoAndJulietAndMe** [comment]
> 需要根据你的视频码率来进行测试。

![image](https://user-images.githubusercontent.com/48921406/123187560-fe4fed80-d4cc-11eb-8207-0f5d36ee2092.png)
作者呀这个执行bash build.sh之后，报这个问题，怎么搞呦
